title: Enhancing GANs with MMD Neural Architecture Search, PMish Activation Function, and Adaptive Rank Decomposition
description: by Prasanna Reddy Pulakurthi, Mahsa Mozaffari, Sohail Dianat, Jamison Heard, Raghuveer Rao, and Majid Rabbani.
google_analytics: 
remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme # add this line to the plugins list if you already have one
